CustomModel_0:
  learning_rate:
    type: float
    range: [1e-4, 1e-3]
    sampling: log
    name: lr

  batch_size:
    type: choice
    options: [32, 64, 128]
    name: batch_size

  # Dropout-related hyperparameters
  dropout_features:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_features

  dropout_combine:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_combine

  # CNN-related hyperparameters
  cnn_1_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_1_filter_size

  cnn_1_kernel_size:
    type: int
    range: [1, 5]
    step: 1
    name: cnn_1_kernel_size

  cnn_1_activation:
    type: choice
    options: ['silu']
    name: cnn_1_activation

  # cnn_1_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_1_dropout_rate

  cnn_2_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2_filter_size

  cnn_2_kernel_size:
    type: int
    range: [1, 5]
    step: 1
    name: cnn_2_kernel_size

  cnn_2_activation:
    type: choice
    options: ['silu']
    name: cnn_2_activation

  # cnn_2_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_2_dropout_rate

  cnn_3_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_3_filter_size

  cnn_3_kernel_size:
    type: int
    range: [1, 5]
    step: 1
    name: cnn_3_kernel_size

  cnn_3_activation:
    type: choice
    options: ['silu']
    name: cnn_3_activation

  # cnn_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_3_dropout_rate

  cnn_4_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_4_filter_size

  cnn_4_kernel_size:
    type: int
    range: [1, 5]
    step: 1
    name: cnn_4_kernel_size

  cnn_4_activation:
    type: choice
    options: ['silu']
    name: cnn_4_activation

  # cnn_4_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_4_dropout_rate

  # LSTM-related hyperparameters
  lstm_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_1_units

  lstm_1_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_1_dropout_rate

  lstm_2_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_2_units

  lstm_2_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_2_dropout_rate

  # Multi-head Attention-related hyperparameters
  multi_head_attention_num_heads:
    type: int
    range: [4, 16]
    step: 4
    name: multi_head_attention_num_heads

  multi_head_attention_key_dim:
    type: int
    range: [32, 128]
    step: 32
    name: multi_head_attention_key_dim

  multi_head_attention_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: multi_head_attention_dropout_rate

  # Dense-related hyperparameters
  dense_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: dense_1_units

  # dense_1_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_1_dropout_rate

  dense_1_activation:
    type: choice
    options: ['silu']
    name: dense_1_activation

  dense_2_units:
    type: int
    range: [64, 512]
    step: 64
    name: dense_2_units

  # dense_2_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_2_dropout_rate

  dense_2_activation:
    type: choice
    options: ['silu']
    name: dense_2_activation

  # dense_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_3_dropout_rate

  dense_3_activation:
    type: choice
    options: ['softmax']
    name: dense_3_activation

CustomModel_1:
  # General hyperparameters
  learning_rate:
    type: float
    range: [1e-4, 1e-3]
    sampling: log
    name: lr

  batch_size:
    type: choice
    options: [32, 64, 128]
    name: batch_size

  # Dropout-related hyperparameters
  dropout_features:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_features

  dropout_combine:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_combine

  # CNN-related hyperparameters
  cnn_1_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_1_filter_size

  cnn_1_kernel_size:
    type: int
    range: [1, 5]
    step: 1
    name: cnn_1_kernel_size

  cnn_1_activation:
    type: choice
    options: ['silu']
    name: cnn_1_activation

  # cnn_1_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_1_dropout_rate


  cnn_2_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2_filter_size

  cnn_2_kernel_size:
    type: int
    range: [1, 4]
    step: 1
    name: cnn_2_kernel_size

  cnn_2_activation:
    type: choice
    options: ['silu']
    name: cnn_2_activation

  # cnn_2_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_2_dropout_rate

  # LSTM-related hyperparameters
  lstm_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_1_units

  lstm_1_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_1_dropout_rate

  lstm_2_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_2_units

  lstm_2_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_2_dropout_rate


  multi_head_attention_num_heads:
    type: int
    range: [4, 16]
    step: 4
    name: multi_head_attention_num_heads

  multi_head_attention_key_dim:
    type: int
    range: [32, 128]
    step: 32
    name: multi_head_attention_key_dim

  multi_head_attention_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: multi_head_attention_dropout_rate

  # Dense-related hyperparameters
  dense_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: dense_1_units

  # dense_1_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_1_dropout_rate

  dense_1_activation:
    type: choice
    options: ['silu']
    name: dense_1_activation

  # dense_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_3_dropout_rate

  dense_3_activation:
    type: choice
    options: ['softmax']
    name: dense_3_activation

CustomModel_2:
  learning_rate:
    type: float
    range: [1e-4, 1e-3]
    sampling: log
    name: lr

  batch_size:
    type: choice
    options: [32, 64, 128]
    name: batch_size

  # Dropout-related hyperparameters
  dropout_features:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_features

  dropout_combine:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_combine

  # LSTM-related hyperparameters
  lstm_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_1_units

  lstm_1_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_1_dropout_rate

  lstm_2_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_2_units

  lstm_2_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_2_dropout_rate

  lstm_3_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_3_units

  lstm_3_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_3_dropout_rate
  # Multi-head Attention-related hyperparameters
  multi_head_attention_num_heads:
    type: int
    range: [4, 16]
    step: 4
    name: multi_head_attention_num_heads

  multi_head_attention_key_dim:
    type: int
    range: [32, 128]
    step: 32
    name: multi_head_attention_key_dim

  multi_head_attention_attributes_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: multi_head_attention_dropout_rate

  # Dense-related hyperparameters
  dense_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: dense_1_units

  # dense_1_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_1_dropout_rate

  dense_1_activation:
    type: choice
    options: ['silu']
    name: dense_1_activation

  dense_2_units:
    type: int
    range: [64, 512]
    step: 64
    name: dense_2_units

  # dense_attributes_2_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_attributes_2_dropout_rate

  dense_2_activation:
    type: choice
    options: ['silu']
    name: dense_2_activation

  # dense_attributes_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_attributes_3_dropout_rate

  dense_3_activation:
    type: choice
    options: ['softmax']
    name: dense_3_activation

CustomModel_3:
  learning_rate:
    type: float
    range: [1e-4, 1e-3]
    sampling: log
    name: lr

  batch_size:
    type: choice
    options: [32, 64, 128]
    name: batch_size

  # Dropout-related hyperparameters
  dropout_features:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_features

  dropout_combine:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_combine

  dropout_attention_pooled:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_attention_pooled

  attention_weight_activation:
    type: choice
    options: ['softmax', 'log_softmax', 'silu', 'tanh', 'sigmoid']
    name: attention_weight_activation

  # CNN-related hyperparameters
  cnn_1_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_1_filter_size

  cnn_1_kernel_size:
    type: int
    range: [1, 4]
    step: 1
    name: cnn_1_kernel_size

  cnn_1_activation:
    type: choice
    options: ['silu']
    name: cnn_1_activation

  # cnn_1_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_1_dropout_rate

  cnn_2_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2_filter_size

  cnn_2_kernel_size:
    type: int
    range: [1, 4]
    step: 1
    name: cnn_2_kernel_size

  cnn_2_activation:
    type: choice
    options: ['silu']
    name: cnn_2_activation

  # cnn_2_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_2_dropout_rate

  # LSTM-related hyperparameters
  lstm_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_1_units

  lstm_1_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_1_dropout_rate

  # Multi-head Attention-related hyperparameters
  multi_head_attention_num_heads:
    type: int
    range: [4, 16]
    step: 4
    name: multi_head_attention_num_heads

  multi_head_attention_key_dim:
    type: int
    range: [32, 128]
    step: 32
    name: multi_head_attention_key_dim

  multi_head_attention_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: multi_head_attention_dropout_rate

  # Dense-related hyperparameters
  dense_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: dense_1_units

  dense_1_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dense_1_dropout_rate

  dense_1_activation:
    type: choice
    options: ['silu']
    name: dense_1_activation

  # dense_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_3_dropout_rate

  dense_3_activation:
    type: choice
    options: ['softmax']
    name: dense_3_activation

CZhouLSTMCNN:
  learning_rate:
    type: float
    range: [1e-4, 1e-3]
    sampling: log
    name: lr

  batch_size:
    type: choice
    options: [32, 64, 128]
    name: batch_size

  # Dropout-related hyperparameters
  dropout_features:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_features

  dropout_combine:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_combine

  # CNN-related hyperparameters (Conv1D)
  cnn_1_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_1_filter_size

  cnn_1_kernel_size:
    type: int
    range: [1, 4]
    step: 1
    name: cnn_1_kernel_size

  cnn_1_activation:
    type: choice
    options: ['silu']
    name: cnn_1_activation

  # cnn_1_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_1_dropout_rate

  cnn_2_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2_filter_size

  cnn_2_kernel_size:
    type: int
    range: [1, 4]
    step: 1
    name: cnn_2_kernel_size


  cnn_2_activation:
    type: choice
    options: ['silu']
    name: cnn_2_activation

  # cnn_2_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_2_dropout_rate

  cnn_3_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_3_filter_size

  cnn_3_kernel_size:
    type: int
    range: [1, 4]
    step: 1
    name: cnn_3_kernel_size


  cnn_3_activation:
    type: choice
    options: ['silu']
    name: cnn_3_activation

  # cnn_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_3_dropout_rate

  cnn_4_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_4_filter_size

  cnn_4_kernel_size:
    type: int
    range: [1, 4]
    step: 1
    name: cnn_4_kernel_size

  cnn_4_activation:
    type: choice
    options: ['silu']
    name: cnn_4_activation

  # cnn_4_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: cnn_4_dropout_rate

  # LSTM-related hyperparameters
  lstm_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_1_units

  lstm_1_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_1_dropout_rate

  lstm_2_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_2_units

  lstm_2_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_2_dropout_rate

  # CNN_2D related hyperparameters
  cnn_2d_1_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2d_1_filter_size

  cnn_2d_1_kernel_size_height:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_1_kernel_size_height
  cnn_2d_1_kernel_size_width:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_1_kernel_size_width

  cnn_2d_1_activation:
    type: choice
    options: ['silu']
    name: cnn_2d_1_activation

  cnn_2d_2_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2d_2_filter_size

  cnn_2d_2_kernel_size_height:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_2_kernel_size_height
  cnn_2d_2_kernel_size_width:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_2_kernel_size_width

  cnn_2d_2_activation:
    type: choice
    options: ['silu']
    name: cnn_2d_2_activation

  dense_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: dense_1_units

  # dense_1_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_1_dropout_rate

  dense_1_activation:
    type: choice
    options: ['silu']
    name: dense_1_activation

  # dense_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_3_dropout_rate

  dense_3_activation:
    type: choice
    options: ['softmax']
    name: dense_3_activation


KimCNN:
  learning_rate:
    type: float
    range: [1e-4, 1e-3]
    sampling: log
    name: lr

  batch_size:
    type: choice
    options: [32, 64, 128]
    name: batch_size

  # Dropout-related hyperparameters
  dropout_features:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_features

  # CNN_2D related hyperparameters
  cnn_2d_1_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2d_1_filter_size

  cnn_2d_1_activation:
    type: choice
    options: ['silu']
    name: cnn_2d_1_activation

  cnn_2d_2_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2d_2_filter_size

  cnn_2d_1_kernel_size_height:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_1_kernel_size_height
  cnn_2d_1_kernel_size_width:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_1_kernel_size_width

  cnn_2d_2_activation:
    type: choice
    options: ['silu']
    name: cnn_2d_2_activation

  cnn_2d_2_kernel_size_height:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_2_kernel_size_height
  cnn_2d_2_kernel_size_width:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_2_kernel_size_width

  # Dense-related hyperparameters


  # dense_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_3_dropout_rate

  dense_3_activation:
    type: choice
    options: ['softmax']
    name: dense_3_activation


PZhouLSTMCNN:
  learning_rate:
    type: float
    range: [1e-4, 1e-3]
    sampling: log
    name: lr

  batch_size:
    type: choice
    options: [32, 64, 128]
    name: batch_size

  # Dropout-related hyperparameters
  dropout_features:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: dropout_features

  # LSTM-related hyperparameters
  lstm_1_units:
    type: int
    range: [64, 512]
    step: 64
    name: lstm_1_units

  lstm_1_dropout_rate:
    type: float
    range: [0.0, 0.5]
    step: 0.1
    name: lstm_1_dropout_rate

  # CNN_2D related hyperparameters
  cnn_2d_1_filter_size:
    type: int
    range: [32, 256]
    step: 32
    name: cnn_2d_1_filter_size

  cnn_2d_1_kernel_size_height:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_1_kernel_size_height


  cnn_2d_1_kernel_size_width:
    type: int
    range: [2, 5]
    step: 1
    name: cnn_2d_1_kernel_size_width

  cnn_2d_1_activation:
    type: choice
    options: ['silu']
    name: cnn_2d_1_activation

  # dense_3_dropout_rate:
  #   type: float
  #   range: [0.0, 0.5]
  #   step: 0.1
  #   name: dense_3_dropout_rate

  dense_3_activation:
    type: choice
    options: ['softmax']
    name: dense_3_activation

Word2Vec:
  sg:
    type: choice
    options: [1, 0]
    name: sg

  vector_size:
    type: int
    range: [100, 300]
    step: 100
    name: vector_size

  window:
    type: int
    range: [3, 10]
    step: 2
    name: window

  min_count:
    type: int
    range: [2, 10]
    step: 2
    name: min_count

  negative:
    type: int
    range: [5, 15]
    step: 5
    name: negative

  sample:
    type: float
    range: [1e-05, 0.001]
    sampling: log
    name: sample

  epochs: 20